// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLZC6VbZsA7fZ03uafyQ9unvZjS9FrrY',
    appId: '1:279198086829:web:2b344ff062e582610d7824',
    messagingSenderId: '279198086829',
    projectId: 'todoappgestion',
    authDomain: 'todoappgestion.firebaseapp.com',
    storageBucket: 'todoappgestion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4Z5Rq_x5Zy6eHfxdNZ75bytAMthnsTI',
    appId: '1:279198086829:android:65e1f8b4a3b9c4ba0d7824',
    messagingSenderId: '279198086829',
    projectId: 'todoappgestion',
    storageBucket: 'todoappgestion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnCjYdxIb67thc_Z7Hsnfxh_thb0ySiM',
    appId: '1:279198086829:ios:4e369dad51e53e400d7824',
    messagingSenderId: '279198086829',
    projectId: 'todoappgestion',
    storageBucket: 'todoappgestion.appspot.com',
    iosBundleId: 'tn.tijotodo.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYnCjYdxIb67thc_Z7Hsnfxh_thb0ySiM',
    appId: '1:279198086829:ios:4e369dad51e53e400d7824',
    messagingSenderId: '279198086829',
    projectId: 'todoappgestion',
    storageBucket: 'todoappgestion.appspot.com',
    iosBundleId: 'tn.tijotodo.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLZC6VbZsA7fZ03uafyQ9unvZjS9FrrY',
    appId: '1:279198086829:web:45846a998fb246090d7824',
    messagingSenderId: '279198086829',
    projectId: 'todoappgestion',
    authDomain: 'todoappgestion.firebaseapp.com',
    storageBucket: 'todoappgestion.appspot.com',
  );
}
